export enum GameActionTypes {
  CREATE_GAME_REQUEST = "CREATE_GAME_REQUEST",
  CREATE_GAME_SUCCESS = "CREATE_GAME_SUCCESS",
  CREATE_GAME_FAILURE = "CREATE_GAME_FAILURE",
  JOIN_TO_GAME_REQUEST = "JOIN_TO_GAME_REQUEST",
  JOIN_TO_GAME_SUCCESS = "JOIN_TO_GAME_SUCCESS",
  JOIN_TO_GAME_FAILURE = "JOIN_TO_GAME_FAILURE",
}
