export enum InviteActionTypes {
  INVITE_SEND = "INVITE_SEND",
  INVITE_SEND_SUCCESS = "INVITE_SEND_SUCCESS",
  INVITE_SEND_FAILURE = "INVITE_SEND_FAILURE",
  INVITE_RECIEVE = "INVITE_RECIEVE",
  INVITE_RECIEVE_SUCCESS = "INVITE_RECIEVE_SUCCESS",
  INVITE_RECIEVE_FAILURE = "INVITE_RECIEVE_FAILURE",
  INVITE_REPLY = "INVITE_REPLY",
  INVITE_REPLY_SUCCESS = "INVITE_REPLY_SUCCESS",
  INVITE_REPLY_FAILURE = "INVITE_REPLY_FAILURE",
  CLEAR_GAME_REDIRECTION = "CLEAR_GAME_REDIRECTION",
}
