export enum ProfileActionTypes {
  UPDATE_PROFILE = "UPDATE_PROFILE",
  UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS",
  UPDATE_PROFILE_FAILURE = "UPDATE_PROFILE_FAILURE",
  PROFILE_REQUEST = "PROFILE_REQUEST",
  PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS",
  PROFILE_REQUEST_FAILURE = "PROFILE_REQUEST_FAILURE",
}
