export enum UserActionTypes {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE",
  USER_LISTENING = "USER_LISTENING",
  USER_LISTENING_SUCCESS = "USER_LISTENING_SUCCESS",
  USER_LISTENING_FAILURE = "USER_LISTENING_FAILURE",
  LOG_OUT = "LOG_OUT",
  LOG_OUT_SUCCESS = "LOG_OUT_SUCCESS",
  UNSET_USER = "UNSET_USER",
  SET_USER = "SET_USER",
}
