export enum UserActionTypes {
  USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST",
  USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS",
  USER_LOGIN_FAILURE = "USER_LOGIN_FAILURE",
  USER_LISTENING = "USER_LISTENING",
  SET_USER = "SET_USER",
  LOG_OUT = "LOG_OUT",
}
